apiVersion: apps/v1
kind: Deployment
metadata:
  name: itta-dev-deployment
  labels:
    app: itta-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: itta-dev
  template:
    metadata:
      labels:
        app: itta-dev
    spec:
      containers:
        - name: itta-dev
          image: itta/itta.dev:latest
          ports:
            - containerPort: 3000
