name: Build and Push Docker Image

on:
  push:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/arm64]

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@v1.5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: itta/itta.dev:${{ github.sha }}
          platforms: ${{ matrix.platform }}

      - name: Clone k8s manifests repo
        uses: actions/checkout@v2
        with:
          repository: itta611/k8s-configs
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: k8s-configs

      - name: Update image tag in k8s manifest
        run: |
          yq e '.spec.template.spec.containers[0].image = "itta/itta.dev:${{ github.sha }}"' -i k8s-configs/itta-dev/${{ github.ref_name }}-deployment.yaml

      - name: Commit and push changes
        run: |
          cd k8s-configs
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update image tag to ${{ github.sha }}"
          git push
